DOMAIN = "unifi_network_rules"

CONF_MAX_RETRIES = "max_retries"
CONF_RETRY_DELAY = "retry_delay"

DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1

CONF_UPDATE_INTERVAL = "update_interval"
DEFAULT_UPDATE_INTERVAL = 5