name: HACS Action

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write
  statuses: write

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: HACS Action
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa
        with:
          category: "integration"
      - name: Report HACS Status
        if: always()
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const conclusion = '${{ job.status }}'.toLowerCase();
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: conclusion === 'success' ? 'success' : 'failure',
              description: conclusion === 'success' ? 'HACS validation passed!' : 'HACS validation failed.',
              context: 'HACS Validation'
            });
