name: Home Assistant Validation

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write
  statuses: write

jobs:
  validate:
    name: Validate with hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb
      - name: Report Hassfest Status
        if: always()
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const conclusion = '${{ job.status }}'.toLowerCase();
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: conclusion === 'success' ? 'success' : 'failure',
              description: conclusion === 'success' ? 'Hassfest validation passed!' : 'Hassfest validation failed.',
              context: 'Hassfest Validation'
            });
